import logo from './logo.png'
import topimg1 from './imgTop1.png'
import topimg2 from './imgTop2.png'
import topimg3 from './imgTop3.png'
import usa from './usa.png'
import uzb from './uz.png'
import rus from './ru.png'
import korea from './kor.png'
import arab from './ar.png'
import tur from './tur.png'
import tarix from './tar.png'
import fizika from './fiz.png'
import matem from './mat.png'
import kimyo from './kim.png'
import bio from './bio.png'
import hamshira from './ham.png'
import web from './web.png'
import desing from './des.png'
import kom from './kom.png'
import it from './it.png'
import kids from './kids.png'
import mental from './mental.png'
import bg from './bg.svg'
import natija1 from './natija1.png'
import natija2 from './natija2.png'
import natija3 from './natija3.png'
import natija4 from './natija4.png'
import max from './max.jpg'
import ser1 from './ser1.jpg'
import ser2 from './ser2.jpg'
import ser3 from './ser3.jpg'
import ser4 from './ser4.jpg'
import ser5 from './ser5.jpg'
import ser6 from './ser6.jpg'
import ser7 from './ser7.jpg'
import ser8 from './ser8.jpg'
import ser9 from './ser9.jpg'
import ser10 from './ser10.jpg'
 


export { max, logo , topimg1 , topimg2 , topimg3 , usa ,uzb , rus , korea , arab , tur , tarix , fizika , matem , kimyo , bio , hamshira , web , desing , kom , it , kids , mental , bg , natija1 , natija2 , natija3 , natija4 , ser1 , ser2 , ser3 , ser4 , ser5 , ser6 , ser7 , ser8 , ser9 , ser10 }